Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 177, in <module>
    train_data, test_data = load_data(aoi, buffer, features)
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 72, in load_data
    eng_test_df = emb_test_df.sort_values(by=['school_locations'])
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/pandas/core/frame.py", line 6909, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/pandas/core/generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'school_locations'