> /Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py(167)load_data()
    166
--> 167     return training_dataset, testing_dataset
    168
            lat        lon  class_x  modis.LC_Type1.mode  modis.LC_Type1.var  ...       383  iso  rurban  dataset     class_y
579  -18.579192  21.993878        1                 10.0            0.000000  ...  1.066333  BWA   rural    train      school
1596 -24.606482  25.925359        0                 13.0            0.000000  ...  1.849497  BWA   urban    train  non_school
494  -22.727692  27.424838        1                 10.0            0.000000  ...  1.153006  BWA   rural    train      school
696  -22.163728  21.853736        1                  7.0            1.250000  ...  1.372616  BWA   rural     test      school
192  -23.127124  26.959331        0                 10.0            0.000000  ...  1.414370  BWA   rural     test  non_school
...         ...        ...      ...                  ...                 ...  ...       ...  ...     ...      ...         ...
1748 -24.738637  25.815763        0                 10.0            0.000000  ...  2.872886  BWA   rural    train  non_school
964  -20.218746  24.138579        1                  7.0            1.250000  ...  2.267402  BWA   rural    train      school
139  -17.782233  25.158068        0                 10.0            0.333333  ...  0.933948  BWA   rural    train  non_school
1603 -20.006561  23.432247        0                 10.0            1.555556  ...  2.958139  BWA   urban    train  non_school
1085 -24.667903  25.927927        1                 13.0            0.000000  ...  4.298803  BWA   urban    train      school
[1824 rows x 444 columns]
Index(['lat', 'lon', 'class_x', 'modis.LC_Type1.mode', 'modis.LC_Type1.var',
       'modis.LC_Type1.evg_conif', 'modis.LC_Type1.evg_broad',
       'modis.LC_Type1.dcd_needle', 'modis.LC_Type1.dcd_broad',
       'modis.LC_Type1.mix_forest',
       ...
       '378', '379', '380', '381', '382', '383', 'iso', 'rurban', 'dataset',
       'class_y'],
      dtype='object', length=444)
*** AttributeError: 'DataFrame' object has no attribute 'label'
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 276, in <module>
    train_data, test_data = load_data(aoi, buffer, features, label)
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 167, in load_data
    return training_dataset, testing_dataset
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 167, in load_data
    return training_dataset, testing_dataset
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
If you suspect this is an IPython 8.7.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True