/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py:196: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  test_latitudes = pd.Series(test_latitudes)
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 241, in <module>
    mlp.run_mlp(
  File "/Users/kelseydoerksen/code/giga-connectivity/classifiers/mlp.py", line 58, in run_mlp
    grid_search.fit(X_train, y_train)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 780, in fit
    self._check_refit_for_multimetric(scorers)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 721, in _check_refit_for_multimetric
    raise ValueError(multimetric_refit_msg)
ValueError: For multi-metric scoring, the parameter refit must be set to a scorer key or a callable to refit an estimator with the best parameter setting on the whole data and make the best_* attributes available for that metric. If this is not needed, refit should be set to False explicitly. True was passed.
Creating instance of MLP model...
Fitting data...
The hard predictions were right 44.32% of the time
Running grid search cv...