2024-02-04 16:58:36,901 INFO    StreamThr :66008 [internal.py:wandb_internal():86] W&B internal server running at pid: 66008, started at: 2024-02-04 16:58:36.901111
2024-02-04 16:58:36,903 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status
2024-02-04 16:58:36,908 INFO    WriterThread:66008 [datastore.py:open_for_write():85] open: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/run-bnkjypow.wandb
2024-02-04 16:58:36,909 DEBUG   SenderThread:66008 [sender.py:send():380] send: header
2024-02-04 16:58:36,934 DEBUG   SenderThread:66008 [sender.py:send():380] send: run
2024-02-04 16:58:36,936 INFO    SenderThread:66008 [sender.py:_maybe_setup_resume():759] checking resume status for None/giga-research/bnkjypow
2024-02-04 16:58:37,471 INFO    SenderThread:66008 [dir_watcher.py:__init__():211] watching files in: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files
2024-02-04 16:58:37,471 INFO    SenderThread:66008 [sender.py:_start_run_threads():1122] run started: bnkjypow with start time 1707065916.902807
2024-02-04 16:58:37,489 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: check_version
2024-02-04 16:58:37,489 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: check_version
2024-02-04 16:58:37,555 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: run_start
2024-02-04 16:58:37,565 DEBUG   HandlerThread:66008 [system_info.py:__init__():32] System info init
2024-02-04 16:58:37,566 DEBUG   HandlerThread:66008 [system_info.py:__init__():47] System info init done
2024-02-04 16:58:37,566 INFO    HandlerThread:66008 [system_monitor.py:start():181] Starting system monitor
2024-02-04 16:58:37,566 INFO    SystemMonitor:66008 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-02-04 16:58:37,566 INFO    HandlerThread:66008 [system_monitor.py:probe():201] Collecting system info
2024-02-04 16:58:37,568 DEBUG   HandlerThread:66008 [system_info.py:probe():196] Probing system
2024-02-04 16:58:37,568 INFO    SystemMonitor:66008 [interfaces.py:start():190] Started cpu monitoring
2024-02-04 16:58:37,569 INFO    SystemMonitor:66008 [interfaces.py:start():190] Started disk monitoring
2024-02-04 16:58:37,569 INFO    SystemMonitor:66008 [interfaces.py:start():190] Started memory monitoring
2024-02-04 16:58:37,572 INFO    SystemMonitor:66008 [interfaces.py:start():190] Started network monitoring
2024-02-04 16:58:37,579 DEBUG   HandlerThread:66008 [system_info.py:_probe_git():181] Probing git
2024-02-04 16:58:37,610 DEBUG   HandlerThread:66008 [system_info.py:_probe_git():189] Probing git done
2024-02-04 16:58:37,611 DEBUG   HandlerThread:66008 [system_info.py:probe():244] Probing system done
2024-02-04 16:58:37,611 DEBUG   HandlerThread:66008 [system_monitor.py:probe():210] {'os': 'macOS-10.16-x86_64-i386-64bit', 'python': '3.10.9', 'heartbeatAt': '2024-02-04T16:58:37.568495', 'startedAt': '2024-02-04T16:58:36.891089', 'docker': None, 'cuda': None, 'args': ('--model', 'gb', '--aoi', 'GIN', '--buffer', '1000', '--root_dir', '/Users/kelseydoerksen/Desktop/Giga', '--experiment_type', 'None'), 'state': 'running', 'program': '/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py', 'codePathLocal': 'run_pipeline.py', 'codePath': 'run_pipeline.py', 'git': {'remote': 'git@github.com:kelsdoerksen/giga-connectivity.git', 'commit': 'f5edce5313fb0c912b1d212f51c4914e31ed0ee7'}, 'email': 'kelseydoerksen@gmail.com', 'root': '/Users/kelseydoerksen/code/giga-connectivity', 'host': 'Kelseys-MacBook-Pro.local', 'username': 'kelseydoerksen', 'executable': '/Users/kelseydoerksen/opt/anaconda3/envs/giga/bin/python', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 2300, 'min': 2300, 'max': 2300}, 'cpu_freq_per_core': [{'current': 2300, 'min': 2300, 'max': 2300}], 'disk': {'/': {'total': 465.62699127197266, 'used': 21.749797821044922}}, 'memory': {'total': 16.0}}
2024-02-04 16:58:37,611 INFO    HandlerThread:66008 [system_monitor.py:probe():211] Finished collecting system info
2024-02-04 16:58:37,611 INFO    HandlerThread:66008 [system_monitor.py:probe():214] Publishing system info
2024-02-04 16:58:37,611 DEBUG   HandlerThread:66008 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-02-04 16:58:37,612 DEBUG   HandlerThread:66008 [system_info.py:_save_pip():68] Saving pip packages done
2024-02-04 16:58:37,612 DEBUG   HandlerThread:66008 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-02-04 16:58:38,474 INFO    Thread-12 :66008 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/conda-environment.yaml
2024-02-04 16:58:38,475 INFO    Thread-12 :66008 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/requirements.txt
2024-02-04 16:58:44,493 INFO    Thread-12 :66008 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/conda-environment.yaml
2024-02-04 16:58:44,620 DEBUG   HandlerThread:66008 [system_info.py:_save_conda():87] Saving conda packages done
2024-02-04 16:58:44,621 INFO    HandlerThread:66008 [system_monitor.py:probe():216] Finished publishing system info
2024-02-04 16:58:44,624 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:58:44,624 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 16:58:44,625 DEBUG   SenderThread:66008 [sender.py:send():380] send: files
2024-02-04 16:58:44,625 INFO    SenderThread:66008 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2024-02-04 16:58:44,633 DEBUG   SenderThread:66008 [sender.py:send():380] send: telemetry
2024-02-04 16:58:44,633 DEBUG   SenderThread:66008 [sender.py:send():380] send: config
2024-02-04 16:58:44,634 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 16:58:44,634 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 16:58:44,635 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 16:58:45,248 INFO    wandb-upload_0:66008 [upload_job.py:push():131] Uploaded file /var/folders/45/0gt2k_f526x1p6241p2jbczr0000gn/T/tmpe76vvmc3wandb/kvrg907k-wandb-metadata.json
2024-02-04 16:58:45,497 INFO    Thread-12 :66008 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/wandb-metadata.json
2024-02-04 16:58:45,497 INFO    Thread-12 :66008 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/output.log
2024-02-04 16:58:47,500 INFO    Thread-12 :66008 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/output.log
2024-02-04 16:58:48,071 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:58:53,083 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:58:58,101 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:58:59,633 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 16:58:59,634 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 16:58:59,634 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 16:59:03,892 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:59:08,909 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:59:09,575 INFO    Thread-12 :66008 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/config.yaml
2024-02-04 16:59:14,086 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:59:14,635 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 16:59:14,636 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 16:59:14,638 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 16:59:19,879 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:59:24,890 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:59:29,651 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 16:59:29,651 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 16:59:29,653 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 16:59:30,852 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:59:35,864 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:59:37,579 DEBUG   SystemMonitor:66008 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-02-04 16:59:37,590 DEBUG   SenderThread:66008 [sender.py:send():380] send: stats
2024-02-04 16:59:41,596 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:59:44,646 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 16:59:44,653 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 16:59:44,657 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 16:59:46,881 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:59:51,896 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:59:56,909 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 16:59:59,647 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 16:59:59,651 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 16:59:59,657 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:00:02,887 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:00:07,584 DEBUG   SenderThread:66008 [sender.py:send():380] send: stats
2024-02-04 17:00:08,593 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:00:13,612 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:00:14,647 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:00:14,648 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:00:14,655 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:00:18,786 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:00:23,798 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:00:28,811 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:00:29,652 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:00:29,653 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:00:29,656 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:00:33,829 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:00:37,586 DEBUG   SenderThread:66008 [sender.py:send():380] send: stats
2024-02-04 17:00:39,600 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:00:44,615 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:00:44,653 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:00:44,653 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:00:44,659 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:00:49,868 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:00:54,881 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:00:59,653 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:00:59,653 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:00:59,661 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:01:00,859 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:05,860 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:07,586 DEBUG   SenderThread:66008 [sender.py:send():380] send: stats
2024-02-04 17:01:11,598 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:14,659 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:01:14,662 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:01:14,669 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:01:16,930 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:21,941 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:26,980 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:29,655 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:01:29,656 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:01:29,668 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:01:32,909 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:37,591 DEBUG   SenderThread:66008 [sender.py:send():380] send: stats
2024-02-04 17:01:38,593 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:43,607 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:44,656 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:01:44,656 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:01:44,669 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:01:48,873 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:53,901 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:58,912 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:01:59,660 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:01:59,660 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:01:59,671 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:02:03,915 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:02:07,600 DEBUG   SenderThread:66008 [sender.py:send():380] send: stats
2024-02-04 17:02:09,606 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:02:14,630 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:02:14,663 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:02:14,663 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:02:14,673 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:02:19,872 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:02:24,892 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:02:29,666 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:02:29,666 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:02:29,675 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:02:29,899 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:02:34,918 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:02:37,601 DEBUG   SenderThread:66008 [sender.py:send():380] send: stats
2024-02-04 17:02:40,615 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:02:44,668 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:02:44,669 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:02:44,677 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:02:45,968 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:02:50,978 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:02:55,990 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:02:59,682 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:02:59,683 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:02:59,684 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:03:01,018 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:03:06,039 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:03:07,596 DEBUG   SenderThread:66008 [sender.py:send():380] send: stats
2024-02-04 17:03:11,622 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:03:14,683 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:03:14,684 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:03:14,684 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:03:16,896 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:03:21,916 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:03:26,932 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:03:29,684 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:03:29,687 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:03:29,688 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:03:32,622 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:03:37,600 DEBUG   SenderThread:66008 [sender.py:send():380] send: stats
2024-02-04 17:03:38,608 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:03:43,636 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:03:44,683 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:03:44,694 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:03:44,695 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:03:48,875 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:05:23,582 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: status_report
2024-02-04 17:05:26,895 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:05:26,898 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: stop_status
2024-02-04 17:05:26,898 DEBUG   SenderThread:66008 [sender.py:send_request():407] send_request: stop_status
2024-02-04 17:05:31,923 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:05:36,940 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:05:41,902 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:05:46,972 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:05:49,169 INFO    SenderThread:66008 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe7716fec50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7716fec50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7716fec50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2024-02-04 17:05:51,998 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:05:56,904 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:06:02,059 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:06:07,075 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:06:58,118 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:07:03,608 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:07:06,715 WARNING FileStreamThread:66008 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fe7715aad40>>, timeout=180), args: ('https://api.wandb.ai/files/kelsey-doerksen/giga-research/bnkjypow/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-02-04 17:07:08,633 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:07:08,804 WARNING FileStreamThread:66008 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/kelsey-doerksen/giga-research/bnkjypow/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe77167e9b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fe7715aad40>>, timeout=180), args: ('https://api.wandb.ai/files/kelsey-doerksen/giga-research/bnkjypow/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-02-04 17:07:13,129 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:07:13,708 WARNING FileStreamThread:66008 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/kelsey-doerksen/giga-research/bnkjypow/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe77167f3d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fe7715aad40>>, timeout=180), args: ('https://api.wandb.ai/files/kelsey-doerksen/giga-research/bnkjypow/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-02-04 17:07:18,669 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:07:22,907 WARNING FileStreamThread:66008 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/kelsey-doerksen/giga-research/bnkjypow/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe77167f3a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fe7715aad40>>, timeout=180), args: ('https://api.wandb.ai/files/kelsey-doerksen/giga-research/bnkjypow/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-02-04 17:07:23,684 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:07:28,133 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:07:33,723 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:07:38,742 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:07:41,526 WARNING FileStreamThread:66008 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/kelsey-doerksen/giga-research/bnkjypow/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe77167f4c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fe7715aad40>>, timeout=180), args: ('https://api.wandb.ai/files/kelsey-doerksen/giga-research/bnkjypow/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-02-04 17:07:43,135 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:07:48,792 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:07:53,803 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:07:58,140 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:08:03,841 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:08:08,850 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:08:13,140 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:09:04,580 WARNING FileStreamThread:66008 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/kelsey-doerksen/giga-research/bnkjypow/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7716ff640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fe7715aad40>>, timeout=180), args: ('https://api.wandb.ai/files/kelsey-doerksen/giga-research/bnkjypow/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-02-04 17:09:04,910 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:09:09,931 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:09:14,489 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:09:19,960 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:09:24,991 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:09:29,491 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:09:35,027 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:09:40,046 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:09:44,492 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:09:50,084 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:09:55,113 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:09:59,494 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:10:05,155 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:11:42,204 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:11:45,835 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:11:51,209 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:11:52,527 WARNING FileStreamThread:66008 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/kelsey-doerksen/giga-research/bnkjypow/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7716ffcd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fe7715aad40>>, timeout=180), args: ('https://api.wandb.ai/files/kelsey-doerksen/giga-research/bnkjypow/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-02-04 17:11:56,230 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:12:47,051 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:12:52,516 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:12:57,527 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:14:33,293 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:14:38,436 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:14:43,463 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:14:48,304 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:14:53,511 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:14:58,523 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:15:03,307 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:22:57,847 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:23:02,807 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:23:06,378 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:23:11,822 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:23:16,892 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:23:21,443 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: internal_messages
2024-02-04 17:23:24,929 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: poll_exit
2024-02-04 17:23:25,933 INFO    memory    :66008 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-02-04 17:23:25,933 DEBUG   SystemMonitor:66008 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-02-04 17:23:25,933 DEBUG   SystemMonitor:66008 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-02-04 17:23:29,917 WARNING StreamThr :66008 [internal.py:is_dead():414] Internal process exiting, parent pid 66000 disappeared
2024-02-04 17:23:29,917 ERROR   StreamThr :66008 [internal.py:wandb_internal():152] Internal process shutdown.
2024-02-04 17:23:29,943 DEBUG   HandlerThread:66008 [handler.py:handle_request():144] handle_request: keepalive
2024-02-04 17:23:29,943 INFO    HandlerThread:66008 [handler.py:finish():844] shutting down handler
2024-02-04 17:23:29,943 INFO    HandlerThread:66008 [system_monitor.py:finish():190] Stopping system monitor
2024-02-04 17:23:29,943 INFO    HandlerThread:66008 [interfaces.py:finish():202] Joined cpu monitor
2024-02-04 17:23:29,943 INFO    HandlerThread:66008 [interfaces.py:finish():202] Joined disk monitor
2024-02-04 17:23:29,943 INFO    HandlerThread:66008 [interfaces.py:finish():202] Joined memory monitor
2024-02-04 17:23:29,943 INFO    HandlerThread:66008 [interfaces.py:finish():202] Joined network monitor
2024-02-04 17:23:29,944 INFO    WriterThread:66008 [datastore.py:close():294] close: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/run-bnkjypow.wandb
2024-02-04 17:23:44,603 INFO    SenderThread:66008 [sender.py:finish():1534] shutting down sender
2024-02-04 17:23:46,009 INFO    SenderThread:66008 [dir_watcher.py:finish():358] shutting down directory watcher
2024-02-04 17:23:46,973 INFO    SenderThread:66008 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/output.log
2024-02-04 17:23:46,973 INFO    SenderThread:66008 [dir_watcher.py:finish():388] scan: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files
2024-02-04 17:23:46,973 INFO    SenderThread:66008 [dir_watcher.py:finish():402] scan save: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/requirements.txt requirements.txt
2024-02-04 17:23:46,973 INFO    SenderThread:66008 [dir_watcher.py:finish():402] scan save: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/output.log output.log
2024-02-04 17:23:46,974 INFO    SenderThread:66008 [dir_watcher.py:finish():402] scan save: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/config.yaml config.yaml
2024-02-04 17:23:46,976 INFO    SenderThread:66008 [dir_watcher.py:finish():402] scan save: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/conda-environment.yaml conda-environment.yaml
2024-02-04 17:23:46,983 INFO    SenderThread:66008 [dir_watcher.py:finish():402] scan save: /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/wandb-metadata.json wandb-metadata.json
2024-02-04 17:23:46,983 INFO    SenderThread:66008 [file_pusher.py:finish():175] shutting down file pusher
2024-02-04 17:23:46,984 INFO    SenderThread:66008 [file_pusher.py:join():181] waiting for file pusher
2024-02-04 17:23:47,883 INFO    wandb-upload_2:66008 [upload_job.py:push():131] Uploaded file /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/config.yaml
2024-02-04 17:23:47,883 INFO    wandb-upload_3:66008 [upload_job.py:push():131] Uploaded file /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/conda-environment.yaml
2024-02-04 17:23:47,883 INFO    wandb-upload_1:66008 [upload_job.py:push():131] Uploaded file /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/requirements.txt
2024-02-04 17:24:06,465 INFO    wandb-upload_0:66008 [upload_job.py:push():131] Uploaded file /Users/kelseydoerksen/code/giga-connectivity/wandb/run-20240204_165836-bnkjypow/files/output.log
2024-02-04 17:24:07,044 INFO    SenderThread:66008 [file_stream.py:finish():595] file stream finish called
2024-02-04 17:24:34,737 INFO    SenderThread:66008 [file_stream.py:finish():599] file stream finish is done
