> /Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py(77)preprocess_samples()
     76     ipdb.set_trace()
---> 77     cols_to_drop = ['connectivity', 'lat', 'lon', 'school_locations', 'giga_id_school']
     78     if exp == 'new_schools':
Traceback (most recent call last):
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 142, in <module>
    Xtrain, Xtest = preprocess_samples(train_df, test_df, model, experiment_type)
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 77, in preprocess_samples
    cols_to_drop = ['connectivity', 'lat', 'lon', 'school_locations', 'giga_id_school']
  File "/Users/kelseydoerksen/code/giga-connectivity/run_pipeline.py", line 77, in preprocess_samples
    cols_to_drop = ['connectivity', 'lat', 'lon', 'school_locations', 'giga_id_school']
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/kelseydoerksen/opt/anaconda3/envs/giga/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
If you suspect this is an IPython 8.7.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True